version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    environment:
      - NODE_ENV=development
